### ISSUE TITLE
Add command for accepting rules

### ISSUE THREAD

**Issue by bdbch** [Devcord/cordlr-roles#3]
It would be cool if a user could use a command like `!accept` or `!join` to add a role which gives a user all channels on a server after he read the rules/informations.

**Comment by AlphaStyle** [comment]
This is a good feature for server admins to have the option to turn this on or off!
But we should also make it so when a person join the server for the first time it will get a PM with instructions that he must read the rules and `!accept` to get permission to talk, etc....

**Comment by bdbch** [comment]
Yep thats exactly what I thought about. It could also be used for other use cases.

**Comment by AlphaStyle** [comment]
```js
{
  // Use the event emitter when a new user join the server
  this.onMemberAdd(this.newUser)
}

{ 
  // When a new user join the server that user will
  // get a default role with no permission to speak.
  newUser(member) {
    member.addRole('roleName')
  }
}
```

Im not sure how to read Direct Messages yet :/

**Comment by bdbch** [comment]
The functionality is still missing in cordlr-loader directly, so we would need to extend it there.
