### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by troygoode** [Devcord/cordlr-roles#4]
When I try to run `!addrole recruits` the bot responds in Discord telling me that "recruits was added to ecce", but I get this error message in my console:

```
2017-03-18T01:15:02.038441+00:00 app[bot.1]: (node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Forbidden
```

I do have a role named "recruits", it is whitelisted, and I am the server administrator.

**Comment by AlphaStyle** [comment]
Does your bot have a role that has **Manage Roles** permission ?

**Comment by troygoode** [comment]
Thanks @AlphaStyle – that was it!
